### ISSUE TITLE
completely disable the use of ublock origin.

### ISSUE THREAD

**Issue by Gameniti** [ingenitdo/Nervenschoner#6]
I found this plugin through an online article and instantly installed it. I didn't notice that it blocks that many banners but I figure it wouldn't do harm if I have it installed anyway.

Since I already use ublock origin and have my filters etc. in there is it possible to completely disable ublock origin in "Nervenschoner"?
The slider in the icon is nice but it sometimes switches back on..

**Comment by ingenitdo** [comment]
Nervenschoner was build to be an easy-to-use plugin based on ublock and was designed for users without much technical knowledge. If you already use ublock and are able to handle its complexity in the settings dialogs, we would recommend to use ublock only. 
You could just add the https://nervenschoner.eu/nervenschoner.txt filter list to you ublock settings because it contains some additional rules.
